// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef _ESP32_GUI_UI_H
#define _ESP32_GUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void SpinAndLargen_Animation(lv_obj_t * TargetObject, int delay);
void LargeBtn_Animation(lv_obj_t * TargetObject, int delay);
void MoveColorToCenter_Animation(lv_obj_t * TargetObject, int delay);
void MoveSettingsToCenter_Animation(lv_obj_t * TargetObject, int delay);
void HideBtn_Animation(lv_obj_t * TargetObject, int delay);
void ShowBtn_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Home_Scr
void ui_Home_Scr_screen_init(void);
extern lv_obj_t * ui_Home_Scr;
extern lv_obj_t * ui_Button1;
void ui_event_Label1(lv_event_t * e);
extern lv_obj_t * ui_Label1;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_ButtonPressCounter;
void ui_event_radioButton(lv_event_t * e);
extern lv_obj_t * ui_radioButton;
extern lv_obj_t * ui_Label4;
void ui_event_hvacButton(lv_event_t * e);
extern lv_obj_t * ui_hvacButton;
extern lv_obj_t * ui_Label5;
void ui_event_frontSensorButton(lv_event_t * e);
extern lv_obj_t * ui_frontSensorButton;
extern lv_obj_t * ui_Label6;
// SCREEN: ui_FrontSensorScreen
void ui_FrontSensorScreen_screen_init(void);
extern lv_obj_t * ui_FrontSensorScreen;
extern lv_obj_t * ui_frontSensorCarImage;
extern lv_obj_t * ui_frontSensorRedZone;
extern lv_obj_t * ui_frontSensorYellowZone;
extern lv_obj_t * ui_frontSensorGreenZone;
// SCREEN: ui_RadioScreen
void ui_RadioScreen_screen_init(void);
extern lv_obj_t * ui_RadioScreen;
// SCREEN: ui_HVACScreen
void ui_HVACScreen_screen_init(void);
extern lv_obj_t * ui_HVACScreen;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_841796653);    // assets/car-front-gui.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
