// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "ui.h"
#include "comms.h"

void btn_clicked(lv_event_t *e)
{
    // Your code here
}

void blue_button_pressed(lv_event_t * e)
{
	// Your code here
}

void updateSetTemperatureLabel(lv_event_t * e)
{
	// Your code here
    lv_obj_t *arc = lv_event_get_target(e);
    int value = lv_arc_get_value(arc);

    AppEvent event = {
        .type = EVENT_AC_TEMP_SET,
        .data.temp_set.temperature = value
    };
    xQueueSend(xAppEventQueue, &event, portMAX_DELAY);

}

void ACOnFunction(lv_event_t * e)
{
	// Your code here
    AppEvent event = { .type = EVENT_AC_ON_OFF };
    xQueueSend(xAppEventQueue, &event, portMAX_DELAY);
}

void ACTemperatureSet(lv_event_t * e)
{
	// Your code here
	lv_obj_t *arc = lv_event_get_target(e);
    int value = lv_arc_get_value(arc);

    AppEvent event = {
        .type = EVENT_AC_TEMP_SET,
        .data.temp_set.temperature = value
    };
    xQueueSend(xAppEventQueue, &event, portMAX_DELAY);
}
