// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "ui.h"
#include "comms.h"

void btn_clicked(lv_event_t *e)
{
    // Your code here
}

void blue_button_pressed(lv_event_t * e)
{
	// Your code here
}

void jebena_funkcija(lv_event_t * e)
{
	// Your code here
	xEventGroupSetBits(
		xGuiButtonEventGroup,				  /* The event group being updated. */
		GUI_APP_EVENT_BUTTON_JEBENI_PRESSED); /* The bits being set. */
}

void updateSetTemperatureLabel(lv_event_t * e)
{
	// Your code here
	lv_obj_t * arc = lv_event_get_target(e);
	int value = lv_arc_get_value(arc);
	xQueueSend(xTempSetQueue, ( void * ) &value, portMAX_DELAY);
}
