// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

void ui_DriverSeatCtrlScreen_screen_init(void)
{
    ui_DriverSeatCtrlScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DriverSeatCtrlScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DriverSeatCtrlScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DriverSeatCtrlScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_DriverSeatCtrlScreen, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DriverSeatCtrlScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DriverSeatCtrlScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DriverSeatCtrlScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DriverSeatCtrlScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_DriverSeatCtrlScreen);
    lv_img_set_src(ui_Image1, &ui_img_seats_driver_240x180_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 32);
    lv_obj_set_y(ui_Image1, 24);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 300);
    lv_obj_set_style_img_recolor(ui_Image1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Image1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ambientTemperatureLabelDriver = lv_label_create(ui_DriverSeatCtrlScreen);
    lv_obj_set_width(ui_ambientTemperatureLabelDriver, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ambientTemperatureLabelDriver, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ambientTemperatureLabelDriver, -9);
    lv_obj_set_y(ui_ambientTemperatureLabelDriver, 9);
    lv_obj_set_align(ui_ambientTemperatureLabelDriver, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_ambientTemperatureLabelDriver, "°C");
    lv_obj_set_style_text_color(ui_ambientTemperatureLabelDriver, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ambientTemperatureLabelDriver, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ambientTemperatureLabelDriver, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_currentTimeDriver = lv_label_create(ui_DriverSeatCtrlScreen);
    lv_obj_set_width(ui_currentTimeDriver, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_currentTimeDriver, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_currentTimeDriver, -135);
    lv_obj_set_y(ui_currentTimeDriver, -100);
    lv_obj_set_align(ui_currentTimeDriver, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_currentTimeDriver, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_currentTimeDriver, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_currentTimeDriver, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_currentDateDriver = lv_label_create(ui_DriverSeatCtrlScreen);
    lv_obj_set_width(ui_currentDateDriver, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_currentDateDriver, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_currentDateDriver, 3);
    lv_obj_set_y(ui_currentDateDriver, -101);
    lv_obj_set_align(ui_currentDateDriver, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_currentDateDriver, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_currentDateDriver, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeButtonDriver = lv_btn_create(ui_DriverSeatCtrlScreen);
    lv_obj_set_width(ui_HomeButtonDriver, 50);
    lv_obj_set_height(ui_HomeButtonDriver, 50);
    lv_obj_set_x(ui_HomeButtonDriver, -135);
    lv_obj_set_y(ui_HomeButtonDriver, -57);
    lv_obj_set_align(ui_HomeButtonDriver, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButtonDriver, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeButtonDriver, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HomeButtonDriver, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeButtonDriver, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeButtonDriver, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_HomeButtonDriver, &ui_img_home32_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HomeButtonDriver, lv_color_hex(0xA3A3A3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HomeButtonDriver, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HomeButtonDriver, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RadioButtonDriver = lv_btn_create(ui_DriverSeatCtrlScreen);
    lv_obj_set_width(ui_RadioButtonDriver, 50);
    lv_obj_set_height(ui_RadioButtonDriver, 50);
    lv_obj_set_x(ui_RadioButtonDriver, -135);
    lv_obj_set_y(ui_RadioButtonDriver, -6);
    lv_obj_set_align(ui_RadioButtonDriver, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RadioButtonDriver, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RadioButtonDriver, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RadioButtonDriver, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RadioButtonDriver, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RadioButtonDriver, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_RadioButtonDriver, &ui_img_radio32_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RadioButtonDriver, lv_color_hex(0xA3A3A3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RadioButtonDriver, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RadioButtonDriver, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HVACButtonDriver = lv_btn_create(ui_DriverSeatCtrlScreen);
    lv_obj_set_width(ui_HVACButtonDriver, 50);
    lv_obj_set_height(ui_HVACButtonDriver, 50);
    lv_obj_set_x(ui_HVACButtonDriver, -135);
    lv_obj_set_y(ui_HVACButtonDriver, 44);
    lv_obj_set_align(ui_HVACButtonDriver, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HVACButtonDriver, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HVACButtonDriver, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HVACButtonDriver, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HVACButtonDriver, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HVACButtonDriver, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_HVACButtonDriver, &ui_img_temp32_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HVACButtonDriver, lv_color_hex(0x5587C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HVACButtonDriver, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HVACButtonDriver, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ParkingButtonDriver = lv_btn_create(ui_DriverSeatCtrlScreen);
    lv_obj_set_width(ui_ParkingButtonDriver, 50);
    lv_obj_set_height(ui_ParkingButtonDriver, 50);
    lv_obj_set_x(ui_ParkingButtonDriver, -135);
    lv_obj_set_y(ui_ParkingButtonDriver, 93);
    lv_obj_set_align(ui_ParkingButtonDriver, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ParkingButtonDriver, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ParkingButtonDriver, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ParkingButtonDriver, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ParkingButtonDriver, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ParkingButtonDriver, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ParkingButtonDriver, &ui_img_park32_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ParkingButtonDriver, lv_color_hex(0xA3A3A3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ParkingButtonDriver, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ParkingButtonDriver, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_HomeButtonDriver, ui_event_HomeButtonDriver, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RadioButtonDriver, ui_event_RadioButtonDriver, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HVACButtonDriver, ui_event_HVACButtonDriver, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ParkingButtonDriver, ui_event_ParkingButtonDriver, LV_EVENT_ALL, NULL);

}
