// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

void ui_DriverSeatCtrlScreen_screen_init(void)
{
    ui_DriverSeatCtrlScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DriverSeatCtrlScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DriverSeatCtrlScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DriverSeatCtrlScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_DriverSeatCtrlScreen, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DriverSeatCtrlScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DriverSeatCtrlScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DriverSeatCtrlScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DriverSeatCtrlScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_DriverSeatCtrlScreen);
    lv_img_set_src(ui_Image1, &ui_img_seats_driver_240x180_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 23);
    lv_obj_set_y(ui_Image1, 17);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_Image1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Image1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateTimeLabel1 = lv_label_create(ui_DriverSeatCtrlScreen);
    lv_obj_set_width(ui_DateTimeLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateTimeLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateTimeLabel1, -1);
    lv_obj_set_y(ui_DateTimeLabel1, -103);
    lv_obj_set_align(ui_DateTimeLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DateTimeLabel1, "HH:MM DD.MM.YYYY.");
    lv_obj_set_style_text_color(ui_DateTimeLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DateTimeLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeButton1 = lv_btn_create(ui_DriverSeatCtrlScreen);
    lv_obj_set_width(ui_HomeButton1, 40);
    lv_obj_set_height(ui_HomeButton1, 40);
    lv_obj_set_x(ui_HomeButton1, -136);
    lv_obj_set_y(ui_HomeButton1, -64);
    lv_obj_set_align(ui_HomeButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HomeButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeButton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RadioButton1 = lv_btn_create(ui_DriverSeatCtrlScreen);
    lv_obj_set_width(ui_RadioButton1, 40);
    lv_obj_set_height(ui_RadioButton1, 40);
    lv_obj_set_x(ui_RadioButton1, -136);
    lv_obj_set_y(ui_RadioButton1, -17);
    lv_obj_set_align(ui_RadioButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RadioButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RadioButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RadioButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RadioButton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RadioButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HVACButton1 = lv_btn_create(ui_DriverSeatCtrlScreen);
    lv_obj_set_width(ui_HVACButton1, 40);
    lv_obj_set_height(ui_HVACButton1, 40);
    lv_obj_set_x(ui_HVACButton1, -136);
    lv_obj_set_y(ui_HVACButton1, 30);
    lv_obj_set_align(ui_HVACButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HVACButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HVACButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HVACButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HVACButton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HVACButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ambientTemperatureLabelDriver = lv_label_create(ui_DriverSeatCtrlScreen);
    lv_obj_set_width(ui_ambientTemperatureLabelDriver, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ambientTemperatureLabelDriver, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ambientTemperatureLabelDriver, -9);
    lv_obj_set_y(ui_ambientTemperatureLabelDriver, 9);
    lv_obj_set_align(ui_ambientTemperatureLabelDriver, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_ambientTemperatureLabelDriver, "°C");
    lv_obj_set_style_text_color(ui_ambientTemperatureLabelDriver, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ambientTemperatureLabelDriver, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ambientTemperatureLabelDriver, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_HomeButton1, ui_event_HomeButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RadioButton1, ui_event_RadioButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HVACButton1, ui_event_HVACButton1, LV_EVENT_ALL, NULL);

}
