// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

void ui_HVACScreen_screen_init(void)
{
    ui_HVACScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HVACScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HVACScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HVACScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_HVACScreen, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_HVACScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_HVACScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_HVACScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_HVACScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_HVACScreen);
    lv_img_set_src(ui_Image3, &ui_img_hvac_background_280x205_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, 24);
    lv_obj_set_y(ui_Image3, 20);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_Image3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Image3, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ambientTemperatureLabelHVAC = lv_label_create(ui_HVACScreen);
    lv_obj_set_width(ui_ambientTemperatureLabelHVAC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ambientTemperatureLabelHVAC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ambientTemperatureLabelHVAC, -10);
    lv_obj_set_y(ui_ambientTemperatureLabelHVAC, 13);
    lv_obj_set_align(ui_ambientTemperatureLabelHVAC, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_ambientTemperatureLabelHVAC, "°C");
    lv_obj_set_style_text_color(ui_ambientTemperatureLabelHVAC, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ambientTemperatureLabelHVAC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ambientTemperatureLabelHVAC, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_currentTimeHVAC = lv_label_create(ui_HVACScreen);
    lv_obj_set_width(ui_currentTimeHVAC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_currentTimeHVAC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_currentTimeHVAC, -135);
    lv_obj_set_y(ui_currentTimeHVAC, -100);
    lv_obj_set_align(ui_currentTimeHVAC, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_currentTimeHVAC, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_currentTimeHVAC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_currentTimeHVAC, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_currentDateHVAC = lv_label_create(ui_HVACScreen);
    lv_obj_set_width(ui_currentDateHVAC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_currentDateHVAC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_currentDateHVAC, 3);
    lv_obj_set_y(ui_currentDateHVAC, -101);
    lv_obj_set_align(ui_currentDateHVAC, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_currentDateHVAC, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_currentDateHVAC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeButtonHVAC = lv_btn_create(ui_HVACScreen);
    lv_obj_set_width(ui_HomeButtonHVAC, 50);
    lv_obj_set_height(ui_HomeButtonHVAC, 50);
    lv_obj_set_x(ui_HomeButtonHVAC, -135);
    lv_obj_set_y(ui_HomeButtonHVAC, -57);
    lv_obj_set_align(ui_HomeButtonHVAC, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButtonHVAC, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeButtonHVAC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HomeButtonHVAC, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeButtonHVAC, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeButtonHVAC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_HomeButtonHVAC, &ui_img_home32_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HomeButtonHVAC, lv_color_hex(0xA3A3A3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HomeButtonHVAC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HomeButtonHVAC, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RadioButtonHVAC = lv_btn_create(ui_HVACScreen);
    lv_obj_set_width(ui_RadioButtonHVAC, 50);
    lv_obj_set_height(ui_RadioButtonHVAC, 50);
    lv_obj_set_x(ui_RadioButtonHVAC, -135);
    lv_obj_set_y(ui_RadioButtonHVAC, -6);
    lv_obj_set_align(ui_RadioButtonHVAC, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RadioButtonHVAC, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RadioButtonHVAC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RadioButtonHVAC, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RadioButtonHVAC, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RadioButtonHVAC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_RadioButtonHVAC, &ui_img_radio32_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RadioButtonHVAC, lv_color_hex(0xA3A3A3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RadioButtonHVAC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RadioButtonHVAC, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HVACButtonHVAC = lv_btn_create(ui_HVACScreen);
    lv_obj_set_width(ui_HVACButtonHVAC, 50);
    lv_obj_set_height(ui_HVACButtonHVAC, 50);
    lv_obj_set_x(ui_HVACButtonHVAC, -135);
    lv_obj_set_y(ui_HVACButtonHVAC, 44);
    lv_obj_set_align(ui_HVACButtonHVAC, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HVACButtonHVAC, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HVACButtonHVAC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HVACButtonHVAC, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HVACButtonHVAC, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HVACButtonHVAC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_HVACButtonHVAC, &ui_img_temp32_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HVACButtonHVAC, lv_color_hex(0x5587C6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HVACButtonHVAC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HVACButtonHVAC, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ParkingButtonHVAC = lv_btn_create(ui_HVACScreen);
    lv_obj_set_width(ui_ParkingButtonHVAC, 50);
    lv_obj_set_height(ui_ParkingButtonHVAC, 50);
    lv_obj_set_x(ui_ParkingButtonHVAC, -135);
    lv_obj_set_y(ui_ParkingButtonHVAC, 93);
    lv_obj_set_align(ui_ParkingButtonHVAC, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ParkingButtonHVAC, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ParkingButtonHVAC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ParkingButtonHVAC, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ParkingButtonHVAC, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ParkingButtonHVAC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ParkingButtonHVAC, &ui_img_park32_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ParkingButtonHVAC, lv_color_hex(0xA3A3A3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ParkingButtonHVAC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ParkingButtonHVAC, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DriverSeatControlButton = lv_btn_create(ui_HVACScreen);
    lv_obj_set_width(ui_DriverSeatControlButton, 20);
    lv_obj_set_height(ui_DriverSeatControlButton, 20);
    lv_obj_set_x(ui_DriverSeatControlButton, -41);
    lv_obj_set_y(ui_DriverSeatControlButton, 49);
    lv_obj_set_align(ui_DriverSeatControlButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DriverSeatControlButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DriverSeatControlButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DriverSeatControlButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DriverSeatControlButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PassSeatControlButton = lv_btn_create(ui_HVACScreen);
    lv_obj_set_width(ui_PassSeatControlButton, 20);
    lv_obj_set_height(ui_PassSeatControlButton, 18);
    lv_obj_set_x(ui_PassSeatControlButton, 87);
    lv_obj_set_y(ui_PassSeatControlButton, 49);
    lv_obj_set_align(ui_PassSeatControlButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PassSeatControlButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PassSeatControlButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PassSeatControlButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PassSeatControlButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ACControlButton = lv_btn_create(ui_HVACScreen);
    lv_obj_set_width(ui_ACControlButton, 20);
    lv_obj_set_height(ui_ACControlButton, 18);
    lv_obj_set_x(ui_ACControlButton, 23);
    lv_obj_set_y(ui_ACControlButton, -21);
    lv_obj_set_align(ui_ACControlButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ACControlButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ACControlButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ACControlButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ACControlButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_HomeButtonHVAC, ui_event_HomeButtonHVAC, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RadioButtonHVAC, ui_event_RadioButtonHVAC, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HVACButtonHVAC, ui_event_HVACButtonHVAC, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ParkingButtonHVAC, ui_event_ParkingButtonHVAC, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DriverSeatControlButton, ui_event_DriverSeatControlButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PassSeatControlButton, ui_event_PassSeatControlButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ACControlButton, ui_event_ACControlButton, LV_EVENT_ALL, NULL);

}
