// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

void ui_Home_Scr_screen_init(void)
{
    ui_Home_Scr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Home_Scr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home_Scr, lv_color_hex(0x111111), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home_Scr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Home_Scr);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, -90);
    lv_obj_set_y(ui_Button1, -49);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 1);
    lv_obj_set_y(ui_Label1, 1);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Button");

    ui_radioButton = lv_btn_create(ui_Home_Scr);
    lv_obj_set_width(ui_radioButton, 100);
    lv_obj_set_height(ui_radioButton, 50);
    lv_obj_set_x(ui_radioButton, -95);
    lv_obj_set_y(ui_radioButton, 5);
    lv_obj_set_align(ui_radioButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_radioButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_radioButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_radioButton);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Radio");

    ui_hvacButton = lv_btn_create(ui_Home_Scr);
    lv_obj_set_width(ui_hvacButton, 100);
    lv_obj_set_height(ui_hvacButton, 50);
    lv_obj_set_x(ui_hvacButton, 76);
    lv_obj_set_y(ui_hvacButton, 18);
    lv_obj_set_align(ui_hvacButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hvacButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_hvacButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_hvacButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_hvacButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(ui_hvacButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_hvacButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label5 = lv_label_create(ui_hvacButton);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "HVAC");

    ui_frontSensorButton = lv_btn_create(ui_Home_Scr);
    lv_obj_set_width(ui_frontSensorButton, 147);
    lv_obj_set_height(ui_frontSensorButton, 50);
    lv_obj_set_x(ui_frontSensorButton, -31);
    lv_obj_set_y(ui_frontSensorButton, 63);
    lv_obj_set_align(ui_frontSensorButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_frontSensorButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_frontSensorButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_frontSensorButton);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Front Sensor");

    ui_currentTimeHome = lv_label_create(ui_Home_Scr);
    lv_obj_set_width(ui_currentTimeHome, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_currentTimeHome, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_currentTimeHome, -115);
    lv_obj_set_y(ui_currentTimeHome, -101);
    lv_obj_set_align(ui_currentTimeHome, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_currentTimeHome, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_currentTimeHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_currentDateHome = lv_label_create(ui_Home_Scr);
    lv_obj_set_width(ui_currentDateHome, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_currentDateHome, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_currentDateHome, 1);
    lv_obj_set_y(ui_currentDateHome, -101);
    lv_obj_set_align(ui_currentDateHome, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_currentDateHome, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_currentDateHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Label1, ui_event_Label1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_radioButton, ui_event_radioButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_hvacButton, ui_event_hvacButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_frontSensorButton, ui_event_frontSensorButton, LV_EVENT_ALL, NULL);

}
