// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonPressChart = lv_chart_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonPressChart, 200);
    lv_obj_set_height(ui_ButtonPressChart, 100);
    lv_obj_set_x(ui_ButtonPressChart, 10);
    lv_obj_set_y(ui_ButtonPressChart, -15);
    lv_obj_set_align(ui_ButtonPressChart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_ButtonPressChart, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_ButtonPressChart, 4);
    lv_chart_set_range(ui_ButtonPressChart, LV_CHART_AXIS_PRIMARY_Y, 0, 20);
    lv_chart_set_axis_tick(ui_ButtonPressChart, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_ButtonPressChart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_ButtonPressChart, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
    lv_chart_series_t * ui_ButtonPressChart_series_1 = lv_chart_add_series(ui_ButtonPressChart, lv_color_hex(0x808080),
                                                                           LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_ButtonPressChart_series_1_array[] = { 0, 0, 0, 0 };
    lv_chart_set_ext_y_array(ui_ButtonPressChart, ui_ButtonPressChart_series_1, ui_ButtonPressChart_series_1_array);




}
